[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "intro-to-parallel-prog"
authors = [{name = "JosephJohn", email = "joseph.john@anu.edu.au"}]
dynamic = ["version", "description"]