#!/bin/bash

#PBS -P vp91
#PBS -q gpuvolta

#PBS -l ncpus=12
#PBS -l ngpus=1
#PBS -l mem=10GB
#PBS -l walltime=00:05:00 

#PBS -N MPI_gpu



module load python3/3.11.0
module load papi/7.0.1
module load openmpi/4.0.1
module load cuda/12.3.2

. /scratch/vp91/Training-Venv/intro-parallel-prog/bin/activate

mpirun -np 4 python3 /scratch/vp91/$USER/intro-to-parallel-programming/python/src/9_mpi_gpu.py
